const CART_ADD_ITEM = "CART_ADD_ITEM";
const CART_UPDATE_QUANTITY = "CART_UPDATE_QUANTITY";
const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";

module.exports = {
  CART_ADD_ITEM,
  CART_REMOVE_ITEM,
  CART_UPDATE_QUANTITY,
};
