const CART_ADD_ITEM = "CART_ADD_ITEM";
const CART_UPDATE_QUANTITY = "CART_UPDATE_QUANTITY";
const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";

const CART_RESET = "CART_RESET";

module.exports = {
  CART_ADD_ITEM,
  CART_REMOVE_ITEM,
  CART_UPDATE_QUANTITY,
  CART_RESET,
  SAVE_SHIPPING_ADDRESS,
};
